# Generated by Django 5.2.4 on 2025-07-11 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customeruser",
            name="contrasena",
        ),
        migrations.RemoveField(
            model_name="customeruser",
            name="correo_electronico",
        ),
        migrations.RemoveField(
            model_name="customeruser",
            name="nombre_completo",
        ),
        migrations.AddField(
            model_name="customeruser",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="empresas.sucursal",
            ),
        ),
    ]
