# Generated by Django 5.2.4 on 2025-07-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_customeruser_contrasena_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customeruser",
            name="activo",
        ),
        migrations.AlterField(
            model_name="customeruser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
