# Generated by Django 5.2.4 on 2025-07-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_customeruser_activo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeruser",
            name="apellido_materno",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="customeruser",
            name="apellido_paterno",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="customeruser",
            name="nombre",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="customeruser",
            name="rol",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("vendedor", "Vendedor"),
                    ("cotador", "Cotador"),
                    ("supervisor", "Supervisor"),
                    ("almacenista", "Almacenista"),
                    ("mesero", "Mesero"),
                    ("cajero", "Cajero"),
                    ("cliente", "Cliente"),
                    ("proveedor", "Proveedor"),
                    ("otro", "Otro"),
                ],
                max_length=50,
            ),
        ),
    ]
