# Generated by Django 5.2.6 on 2025-09-19 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=255)),
                ("rfc", models.CharField(max_length=13, unique=True)),
                ("direccion", models.TextField(blank=True, null=True)),
                ("correo", models.EmailField(blank=True, max_length=254, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "Sucursal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clientes",
                        to="empresas.sucursal",
                    ),
                ),
                (
                    "empresa_facturadora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientes_facturados",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "empresa_registradora",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientes_registrados",
                        to="empresas.empresa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uso_cfdi", models.CharField(max_length=5)),
                ("forma_pago", models.CharField(max_length=5)),
                ("metodo_pago", models.CharField(max_length=5)),
                ("regimen_fiscal_receptor", models.CharField(max_length=5)),
                ("tipo_comprobante", models.CharField(default="I", max_length=1)),
                ("uuid", models.CharField(max_length=100, unique=True)),
                ("sello_digital", models.TextField(blank=True, null=True)),
                ("cadena_original", models.TextField(blank=True, null=True)),
                (
                    "archivo_xml",
                    models.FileField(blank=True, null=True, upload_to="facturas/xml/"),
                ),
                (
                    "archivo_pdf",
                    models.FileField(blank=True, null=True, upload_to="facturas/pdf/"),
                ),
                ("fecha_emision", models.DateTimeField(auto_now_add=True)),
                ("estatus", models.CharField(default="emitida", max_length=20)),
                (
                    "cliente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="facturacion.cliente",
                    ),
                ),
                (
                    "venta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="ventas.venta"
                    ),
                ),
            ],
        ),
    ]
