# Generated by Django 5.2.3 on 2025-06-27 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0001_initial"),
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientocontable",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="empresas.sucursal",
            ),
        ),
    ]
