# Generated by Django 5.2.3 on 2025-09-03 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Paquete', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_empresas/')),
                ('calle', models.TextField(blank=True, null=True)),
                ('numero_exterior', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_interior', models.CharField(blank=True, max_length=10, null=True)),
                ('colonia', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(default='México', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('tipo_empresa', models.CharField(choices=[('retail', 'Retail'), ('servicios', 'Servicios'), ('manufactura', 'Manufactura'), ('distribucion', 'Distribución'), ('salud', 'Salud'), ('educacion', 'Educación'), ('restaurante', 'Restaurante'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('es_matriz', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='Paquete.paquete')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='empresas.empresa')),
            ],
        ),
    ]
