# Generated by Django 5.2.4 on 2025-07-10 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("rfc", models.CharField(max_length=13, unique=True)),
                ("direccion", models.TextField(blank=True, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "correo_electronico",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("direccion", models.TextField(blank=True, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "correo_electronico",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sucursales",
                        to="empresas.empresa",
                    ),
                ),
            ],
        ),
    ]
