# Generated by Django 5.2.4 on 2025-07-16 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Paquete", "0001_initial"),
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empresa",
            name="direccion",
        ),
        migrations.AddField(
            model_name="empresa",
            name="calle",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="ciudad",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="codigo_postal",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="colonia",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="estado",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="numero_exterior",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="numero_interior",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="pais",
            field=models.CharField(default="México", max_length=100),
        ),
        migrations.AddField(
            model_name="empresa",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empresas",
                to="Paquete.paquete",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="tipo_empresa",
            field=models.CharField(
                choices=[
                    ("retail", "Retail"),
                    ("servicios", "Servicios"),
                    ("manufactura", "Manufactura"),
                    ("distribucion", "Distribución"),
                    ("restaurante", "Restaurante"),
                    ("otro", "Otro"),
                ],
                default="otro",
                max_length=20,
            ),
        ),
    ]
