# Generated by Django 5.2.4 on 2025-08-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0002_remove_empresa_direccion_empresa_calle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos_empresas/"),
        ),
    ]
