# Generated by Django 5.2.3 on 2025-08-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0003_empresa_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="es_matriz",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="rfc",
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
