# Generated by Django 5.2.6 on 2025-09-19 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria de Productos",
                "verbose_name_plural": "Categorias de Productos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="InventarioSucursal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_actual", models.IntegerField(default=0)),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventarios",
                        to="empresas.sucursal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[
                            ("entrada", "Entrada"),
                            ("salida", "Salida"),
                            ("ajuste", "Ajuste"),
                        ],
                        max_length=10,
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("fecha_movimiento", models.DateTimeField(auto_now_add=True)),
                (
                    "inventario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productos.inventariosucursal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "codigo_barras",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("precio_venta", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "costo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "quien_registro",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="productos/"),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="productos.categoriaproducto",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productos",
                        to="empresas.empresa",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="inventariosucursal",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventarios",
                to="productos.producto",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventariosucursal",
            unique_together={("sucursal", "producto")},
        ),
    ]
