# Generated by Django 5.2.4 on 2025-07-11 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="quiene_registro",
            new_name="quien_registro",
        ),
    ]
