# Generated by Django 5.2.6 on 2025-09-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriaproducto",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="categoriaproducto",
            unique_together={("nombre", "empresa")},
        ),
    ]
