# Generated by Django 5.2.6 on 2025-09-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoriaproducto",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Categoria de Productos",
                "verbose_name_plural": "Categorias de Productos",
            },
        ),
        migrations.AlterUniqueTogether(
            name="categoriaproducto",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="producto",
            name="codigo_barras",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name="categoriaproducto",
            name="sucursal",
        ),
    ]
