# Generated by Django 5.2.4 on 2025-07-16 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0002_remove_empresa_direccion_empresa_calle_and_more"),
        ("productos", "0002_rename_quiene_registro_producto_quien_registro"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoriaproducto",
            name="empresa",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="empresas.empresa",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="empresa",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="empresas.empresa",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="categoriaproducto",
            unique_together={("nombre", "empresa")},
        ),
    ]
