# Generated by Django 5.2.6 on 2025-09-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_alter_categoriaproducto_nombre_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="imagen",
        ),
        migrations.AddField(
            model_name="producto",
            name="imagen_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="unidad_medida",
            field=models.CharField(
                choices=[
                    ("PZA", "Pieza / Unidad"),
                    ("PESO", "Peso (e.g.,  Kg, gr, lb, oz)"),
                    ("LITRO", "Litros (e.g., Lt, ml)"),
                ],
                default="PZA",
                max_length=10,
                verbose_name="Unidad de Medida",
            ),
        ),
    ]
