# Generated by Django 5.2.6 on 2025-10-03 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
        ("productos", "0003_remove_producto_imagen_producto_imagen_url_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoriaproducto",
            options={
                "ordering": ["nivel", "categoria_padre__nombre", "nombre"],
                "verbose_name": "Categoria de Productos",
                "verbose_name_plural": "Categorias de Productos",
            },
        ),
        migrations.AlterUniqueTogether(
            name="categoriaproducto",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="categoriaproducto",
            name="categoria_padre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategorias",
                to="productos.categoriaproducto",
            ),
        ),
        migrations.AddField(
            model_name="categoriaproducto",
            name="nivel",
            field=models.PositiveIntegerField(
                default=0,
                help_text="0=Principal, 1=Subcategoría, 2=Sub-subcategoría, etc.",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="categoriaproducto",
            unique_together={("nombre", "empresa", "categoria_padre")},
        ),
    ]
