# Generated by Django 5.2.4 on 2025-07-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormaPago",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="MetodoPago",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="RegimenFiscal",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("persona_fisica", models.BooleanField(default=False)),
                ("persona_moral", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UsoCFDI",
            fields=[
                (
                    "clave",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("persona_fisica", models.BooleanField(default=False)),
                ("persona_moral", models.BooleanField(default=False)),
            ],
        ),
    ]
