# Generated by Django 5.2.3 on 2025-09-03 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=255)),
                ("correo_electronico", models.EmailField(max_length=254, unique=True)),
                ("contrasena", models.CharField(max_length=128)),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("vendedor", "Vendedor"),
                            ("cotador", "Cotador"),
                            ("supervisor", "Supervisor"),
                            ("almacenista", "Almacenista"),
                        ],
                        max_length=50,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="empresas.empresa",
                    ),
                ),
            ],
        ),
    ]
