# Generated by Django 5.2.3 on 2025-09-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_mesual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_anual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_gratuito', models.BooleanField(default=False)),
                ('limite_sucursales', models.PositiveIntegerField(default=1)),
                ('limite_usuarios', models.PositiveIntegerField(default=1)),
                ('limite_productos', models.PositiveIntegerField(default=100)),
                ('incluye_soporte', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
